CREATE TABLE users (
    ID INT NOT NULL AUTO_INCREMENT,
    role VARCHAR(16) NOT NULL DEFAULT 'user',   
    email VARCHAR(64) UNIQUE NOT NULL,
    username VARCHAR(16) UNIQUE NOT NULL,
    password VARCHAR(128) NOT NULL,   
    dateRegistered DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (role) REFERENCES roles (name) ON DELETE CASCADE
);
