CREATE TABLE dogs (
      ID INT NOT NULL AUTO_INCREMENT,
      name VARCHAR(32) NOT NULL,
      breed TEXT NOT NULL,
      sex VARCHAR(8) NOT NULL,
      age INT NOT NULL,
      imageURL VARCHAR(2048),
      favourite BOOL NOT NULL DEFAULT 0,
      dateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
      dateModified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (ID)
);